### ISSUE TITLE
2 typos in 1b

### ISSUE THREAD

**Issue by kalmant** [ftsrg-edu/swsv-labs#4]
In `1b-Source-code-analysis-tools.md`:
+ At the end of the 11th line, there should be an "**it**", right before the full stop
+ The first "**it**" after the open parenthesis in line 80 shouldn't be there

Sidenote: It appears that pull requests can not be created for a Wiki page since forks do not include the Wiki. The Wiki repositories themselves can only be cloned (by appending `.wiki.git` to the end of the repository's name, e.g. `https://github.com/FTSRG/swsv-labs.wiki.git`).

**Comment by micskeiz** [comment]
Thanks, fixed!
