### ISSUE TITLE
Advanced static analysis tools - Links Broken

### ISSUE THREAD

**Issue by matthewtuby** [ftsrg-edu/swsv-labs#5]
Under the following wiki page:
https://github.com/ftsrg/swsv-labs/wiki/1-Advanced-static-analysis-tools
Links to [fbinfer](https://fbinfer.com) are broken.

Solution: From the ends of all [https://fbinfer.com/](https://fbinfer.com) links ".html" should be removed.
Example solution:
The original link: https://fbinfer.com/docs/getting-started.html
The replacement that works: https://fbinfer.com/docs/getting-started

Screencap of the an example issue:
![asd](https://user-images.githubusercontent.com/29383054/92989541-888e0e80-f4c4-11ea-82dd-de7e5c800bb9.png)

**Comment by micskeiz** [comment]
Thanks, we fixed the broken links!

**Comment by hajduakos** [comment]
I've double checked all of the links and it works to me. Thanks for your feedback, closing the issue now.
